"""Canonical domain layer for universal opportunity intake and execution."""

from .adapters import SAMGovClient, SAMGovSource, normalize_sam_record
from .domain import (
    EvidenceAssessment,
    EvidencePacket,
    MissionCandidate,
    Opportunity,
    ProvenanceRecord,
    QualificationDecision,
    QualificationStatus,
    to_primitive,
)
from .execution import (
    EXECUTION_PLAN_SCHEMA_VERSION,
    ApprovalRequirement,
    ExecutionPlan,
    ExecutionPlanStatus,
    ExecutionPolicy,
    ExecutionStep,
    ExecutionStepKind,
)
from .execution_record import (
    EXECUTION_RECORD_SCHEMA_VERSION,
    ExecutionArtifact,
    ExecutionEvent,
    ExecutionEventStore,
    ExecutionEventType,
    ExecutionOutcome,
    ExecutionOutcomeStatus,
    ExecutionRecorder,
    ExecutionRun,
    ExecutionRunStatus,
    InMemoryExecutionEventStore,
    derive_status,
)
from .graph import (
    MISSION_GRAPH_SCHEMA_VERSION,
    MissionGraph,
    MissionGraphEdge,
    MissionGraphNode,
    build_mission_graph,
)
from .integration import (
    ENGINE_VERSION,
    RUN_MANIFEST_SCHEMA_VERSION,
    ArtifactSink,
    DailyIntakeResult,
    IntakeArtifactBundle,
    JsonDirectoryArtifactSink,
    UniversalDailyIntakeBridge,
)
from .lifecycle import ExecutionContext, ExecutionLifecycle
from .orchestrator import (
    DeterministicExecutionOrchestrator,
    OrchestrationState,
    StepState,
    StepStatus,
    replay_orchestration_state,
)
from .pipeline import (
    QualificationPolicy,
    UniversalIntakeAdapter,
    build_mission_candidate,
)
from .runtime import (
    Capability,
    ExecutionArtifactResult,
    ExecutionPlugin,
    ExecutionResult,
    NoOpPlugin,
    PluginRegistrationError,
    PluginRegistry,
    PluginResolutionError,
    PluginRuntime,
    required_capabilities,
    route_plugin,
)
from .sources import OpportunitySource, SourceMetadata, collect_normalized
from .sqlite_store import SQLiteExecutionEventStore

__all__ = [
    "ApprovalRequirement",
    "ArtifactSink",
    "Capability",
    "DailyIntakeResult",
    "DeterministicExecutionOrchestrator",
    "ENGINE_VERSION",
    "EXECUTION_PLAN_SCHEMA_VERSION",
    "EXECUTION_RECORD_SCHEMA_VERSION",
    "EvidenceAssessment",
    "EvidencePacket",
    "ExecutionArtifact",
    "ExecutionArtifactResult",
    "ExecutionContext",
    "ExecutionEvent",
    "ExecutionEventStore",
    "ExecutionEventType",
    "ExecutionLifecycle",
    "ExecutionOutcome",
    "ExecutionOutcomeStatus",
    "ExecutionPlan",
    "ExecutionPlanStatus",
    "ExecutionPlugin",
    "ExecutionPolicy",
    "ExecutionRecorder",
    "ExecutionResult",
    "ExecutionRun",
    "ExecutionRunStatus",
    "ExecutionStep",
    "ExecutionStepKind",
    "InMemoryExecutionEventStore",
    "IntakeArtifactBundle",
    "JsonDirectoryArtifactSink",
    "MISSION_GRAPH_SCHEMA_VERSION",
    "MissionCandidate",
    "MissionGraph",
    "MissionGraphEdge",
    "MissionGraphNode",
    "NoOpPlugin",
    "Opportunity",
    "OpportunitySource",
    "OrchestrationState",
    "PluginRegistrationError",
    "PluginRegistry",
    "PluginResolutionError",
    "PluginRuntime",
    "ProvenanceRecord",
    "QualificationDecision",
    "QualificationPolicy",
    "QualificationStatus",
    "RUN_MANIFEST_SCHEMA_VERSION",
    "SAMGovClient",
    "SAMGovSource",
    "SQLiteExecutionEventStore",
    "SourceMetadata",
    "StepState",
    "StepStatus",
    "UniversalDailyIntakeBridge",
    "UniversalIntakeAdapter",
    "build_mission_candidate",
    "build_mission_graph",
    "collect_normalized",
    "derive_status",
    "normalize_sam_record",
    "replay_orchestration_state",
    "required_capabilities",
    "route_plugin",
    "to_primitive",
]
